### ISSUE TITLE
Asks from Dell Med: 1) county trends on the Covid related ER visits (7d rolling average); 2) new lab confirmed covid admissions by county & region (7d rolling average); testing trend by county similar to what's on state page

### ISSUE THREAD

**Issue by LisaKirsch-DellMed** [texas-2036/covid_tracker#55] opened 2020-05-19 14:41 UTC

**Comment by mrworthington** [comment] 2020-05-19 15:05
Asks from Dell Med: 

- [ ] county trends on the Covid related ER visits (7d rolling average); 
- [ ] new lab confirmed covid admissions by county & region (7d rolling average)
- [ ] testing trend by county similar to what's on state page

**Comment by mrworthington** [comment] 2020-05-28 19:00
Since 2 of these are done. I’m closing this and moving the last item to a new issue so we keep track of what’s done and what isn’t

**Closed** 2020-05-28 19:00 UTC
Labels: dell med request

**Comment by LisaKirsch-DellMed** [comment] 2020-05-28 20:51
Thanks Matt – The website additions look great. I let Parker, Mark, and team know about them, and they were glad to see them.

----

LISA KIRSCH, MPAff
Senior Policy Director

Dell Medical School  |  The University of Texas at Austin
o: 512-495-5131  |  dellmedschool.utexas.edu
